### PR TITLE
de-DE include new ruleset translations

### PR DESCRIPTION
**Pull request by bastik-tor**

### CODE REVIEW

**Comment by bastik-tor** [comment]
Now this request contains the translation for the tiny version. I think I kept them as short as possible.

**Comment by bastik-tor** [comment]
I know that you cherry-pick, but I better notify you that I also edited the readme to include a translation section to make it very easy to see what translations exist and so on.

**Comment by futpib** [comment]
Awesome

**Comment by futpib** [comment]
9539bb251abfd01bd7220e21039fa4b587b60abf 2494c6a5c640caa655758037e5991a93505631cc

**Pull request closed without merging**
